[package]
name = "flowi_sw_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = "0.6"
simd = { path = "../simd" }
color16 = { path = "../color16" }
flowi-renderer = { path = "../flowi-renderer" }

