[workspace]
resolver = "2"
members = [
    "crates/arena-allocator",
    "crates/fileorama",
    "crates/flowi_core",
    "crates/ui_raster",
    "main",
    "test_bed", 
]

[profile.dev.package.zune-png]
opt-level = 3

[profile.dev.package.zune-jpeg]
opt-level = 3

[profile.dev.package.resvg]
opt-level = 3

[profile.release]
opt-level = 2
