[workspace]
resolver = "2"
members = [
    "fileorama",
    "flowi_core",
    "flowi",
    "main",
]
exclude = [
    "tools/api_gen", 
]

[profile.dev.package.zune-png]
opt-level = 3

[profile.dev.package.zune-jpeg]
opt-level = 3

[profile.dev.package.resvg]
opt-level = 3


