-- vim: noexpandtab ts=4 sw=4
require "tundra.syntax.rust-cargo"
require "tundra.syntax.dotnet"
local native = require "tundra.native"
local path = require "tundra.path"

local function get_src(dir, recursive)
	return FGlob {
		Dir = dir,
		Extensions = { ".cpp", ".c", ".h", ".s", ".m" },
		Filters = {
			{ Pattern = "{/\\}_unittest{/\\}"; Config = "win32-*" },
			{ Pattern = "{/\\}_win{/\\}"; Config = "win32-*" },
			{ Pattern = "{/\\}_macos{/\\}"; Config = "mac*-*" },
			{ Pattern = "{/\\}_linux{/\\}"; Config = "linux-*" },
			{ Pattern = "{/\\}_posix{/\\}"; Config = { "mac*-*", "linux-*" } },
		},
		Recursive = recursive and true or false,
	}
end

local angle_dir = "external/angle/"
local common_dir = angle_dir .. "src/common/"
local samples_dir = angle_dir .. "samples/"
local util_dir = angle_dir .. "util/"

-- Common sources/headers
local common = {
	common_dir .. "aligned_memory.cpp",
	common_dir .. "aligned_memory.h",
	common_dir .. "android_util.cpp",
	common_dir .. "android_util.h",
	common_dir .. "angleutils.cpp",
	common_dir .. "angleutils.h",
	common_dir .. "apple_platform_utils.h",
	common_dir .. "bitset_utils.h",
	common_dir .. "Color.h",
	common_dir .. "debug.cpp",
	common_dir .. "debug.h",
	common_dir .. "event_tracer.cpp",
	common_dir .. "event_tracer.h",
	common_dir .. "FastVector.h",
	common_dir .. "FixedVector.h",
	common_dir .. "Float16ToFloat32.cpp",
	common_dir .. "hash_utils.h",
	common_dir .. "mathutil.cpp",
	common_dir .. "mathutil.h",
	common_dir .. "matrix_utils.cpp",
	common_dir .. "matrix_utils.h",
	common_dir .. "MemoryBuffer.cpp",
	common_dir .. "MemoryBuffer.h",
	common_dir .. "Optional.h",
	common_dir .. "PackedEGLEnums_autogen.cpp",
	common_dir .. "PackedEGLEnums_autogen.h",
	common_dir .. "PackedEnums.cpp",
	common_dir .. "PackedEnums.h",
	common_dir .. "PackedGLEnums_autogen.cpp",
	common_dir .. "PackedGLEnums_autogen.h",
	common_dir .. "platform.h",
	common_dir .. "PoolAlloc.cpp",
	common_dir .. "PoolAlloc.h",
	common_dir .. "string_utils.cpp",
	common_dir .. "string_utils.h",
	common_dir .. "system_utils.cpp",
	common_dir .. "system_utils.h",
	{ common_dir .. "system_utils_linux.cpp"; Config = "linux-*" },
	{ common_dir .. "system_utils_mac.cpp"; Config = "mac*-*" },
	{ common_dir .. "system_utils_posix.cpp"; Config = { "linux-*", "mac*-*" } },
	{ common_dir .. "system_utils_win32.cpp"; Config = "win32-*" },
	{ common_dir .. "system_utils_win.cpp"; Config = "win32-*" },
	{ common_dir .. "system_utils_winuwp.cpp"; Config = "win32-*" },
	common_dir .. "tls.cpp",
	common_dir .. "tls.h",
	common_dir .. "uniform_type_info_autogen.cpp",
	common_dir .. "utilities.cpp",
	common_dir .. "utilities.h",
	common_dir .. "vector_utils.h",
	common_dir .. "version.h",
	get_src(common_dir .. "third_party", true),
}

-- "Ported" from external/angle/src/libANGLEGLESv2.gni

local xxhash_sources = {
	angle_dir .. "src/common/third_party/xxhash/xxhash.c",
	angle_dir .. "src/common/third_party/xxhash/xxhash.h",
}

local angle_system_utils_sources = {
	angle_dir .. "src/common/Optional.h",
	angle_dir .. "src/common/angleutils.h",
	angle_dir .. "src/common/platform.h",
	angle_dir .. "src/common/system_utils.cpp",
	angle_dir .. "src/common/system_utils.h",
}

local libangle_image_util_headers = {
	angle_dir .. "src/image_util/copyimage.h",
	angle_dir .. "src/image_util/copyimage.inc",
	angle_dir .. "src/image_util/generatemip.h",
  	angle_dir .. "src/image_util/generatemip.inc",
  	angle_dir .. "src/image_util/imageformats.h",
  	angle_dir .. "src/image_util/loadimage.h",
  	angle_dir .. "src/image_util/loadimage.inc",
}

local libangle_image_util_sources = {
  	angle_dir .. "src/image_util/copyimage.cpp",
  	angle_dir .. "src/image_util/imageformats.cpp",
  	angle_dir .. "src/image_util/loadimage.cpp",
  	angle_dir .. "src/image_util/loadimage_etc.cpp",
}

local libangle_gpu_info_util_sources = {
  	angle_dir .. "src/gpu_info_util/SystemInfo.cpp",
  	angle_dir .. "src/gpu_info_util/SystemInfo.h",
  	angle_dir .. "src/gpu_info_util/SystemInfo_internal.h",
}

local libangle_gpu_info_util_win_sources = { angle_dir .."src/gpu_info_util/SystemInfo_win.cpp" }
local libangle_gpu_info_util_android_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_android.cpp" }
local libangle_gpu_info_util_linux_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_linux.cpp" }
local libangle_gpu_info_util_fuchsia_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_fuchsia.cpp" }
local libangle_gpu_info_util_libpci_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_libpci.cpp" }
local libangle_gpu_info_util_x11_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_x11.cpp" }
local libangle_gpu_info_util_mac_sources = { angle_dir .. "src/gpu_info_util/SystemInfo_macos.mm" }
local libangle_gpu_info_util_vulkan_sources = {
  	angle_dir .. "src/gpu_info_util/SystemInfo_vulkan.cpp",
  	angle_dir .. "src/gpu_info_util/SystemInfo_vulkan.h",
}

local libangle_includes = {
  	angle_dir .. "include/angle_gl.h",
  	angle_dir .. "include/export.h",
  	angle_dir .. "include/EGL/egl.h",
  	angle_dir .. "include/EGL/eglext.h",
  	angle_dir .. "include/EGL/eglext_angle.h",
  	angle_dir .. "include/EGL/eglplatform.h",
  	angle_dir .. "include/GLES/gl.h",
  	angle_dir .. "include/GLES/glplatform.h",
  	angle_dir .. "include/GLES/glext.h",
  	angle_dir .. "include/GLES/glext_angle.h",
  	angle_dir .. "include/GLES/glext_explicit_context_autogen.inc",
  	angle_dir .. "include/GLES2/gl2.h",
  	angle_dir .. "include/GLES2/gl2ext.h",
  	angle_dir .. "include/GLES2/gl2ext_angle.h",
  	angle_dir .. "include/GLES2/gl2ext_explicit_context_autogen.inc",
  	angle_dir .. "include/GLES2/gl2platform.h",
  	angle_dir .. "include/GLES3/gl3.h",
  	angle_dir .. "include/GLES3/gl3ext_explicit_context_autogen.inc",
  	angle_dir .. "include/GLES3/gl3platform.h",
  	angle_dir .. "include/GLES3/gl31.h",
  	angle_dir .. "include/GLES3/gl31ext_explicit_context_autogen.inc",
  	angle_dir .. "include/GLES3/gl32.h",
  	angle_dir .. "include/GLES3/gl32ext_explicit_context_autogen.inc",
  	angle_dir .. "include/KHR/khrplatform.h",
  	angle_dir .. "include/WGL/wgl.h",
  	angle_dir .. "include/platform/Feature.h",
  	angle_dir .. "include/platform/FeaturesD3D.h",
  	angle_dir .. "include/platform/FeaturesGL.h",
  	angle_dir .. "include/platform/FeaturesMtl.h",
  	angle_dir .. "include/platform/FeaturesVk.h",
  	angle_dir .. "include/platform/FrontendFeatures.h",
  	angle_dir .. "include/platform/Platform.h",
  	angle_dir .. "include/vulkan/vulkan_fuchsia_ext.h",
}

local libangle_headers = {
  	angle_dir .. "src/libANGLE/AttributeMap.h",
  	angle_dir .. "src/libANGLE/BinaryStream.h",
  	angle_dir .. "src/libANGLE/BlobCache.h",
  	angle_dir .. "src/libANGLE/Buffer.h",
  	angle_dir .. "src/libANGLE/Caps.h",
  	angle_dir .. "src/libANGLE/Compiler.h",
  	angle_dir .. "src/libANGLE/Config.h",
  	angle_dir .. "src/libANGLE/Constants.h",
  	angle_dir .. "src/libANGLE/Context.h",
  	angle_dir .. "src/libANGLE/Context.inl.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_1_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_2_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_3_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_4_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_1_5_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_2_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_2_1_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_3_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_3_1_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_3_2_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_3_3_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_1_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_2_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_3_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_4_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_5_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gl_4_6_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_1_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_2_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_3_0_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_3_1_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_3_2_autogen.h",
  	angle_dir .. "src/libANGLE/Context_gles_ext_autogen.h",
  	angle_dir .. "src/libANGLE/Debug.h",
  	angle_dir .. "src/libANGLE/Device.h",
  	angle_dir .. "src/libANGLE/Display.h",
  	angle_dir .. "src/libANGLE/EGLSync.h",
  	angle_dir .. "src/libANGLE/Error.h",
  	angle_dir .. "src/libANGLE/Error.inc",
  	angle_dir .. "src/libANGLE/ErrorStrings.h",
  	angle_dir .. "src/libANGLE/Fence.h",
  	angle_dir .. "src/libANGLE/Framebuffer.h",
  	angle_dir .. "src/libANGLE/FramebufferAttachment.h",
  	angle_dir .. "src/libANGLE/GLES1Renderer.h",
  	angle_dir .. "src/libANGLE/GLES1Shaders.inc",
  	angle_dir .. "src/libANGLE/GLES1State.h",
  	angle_dir .. "src/libANGLE/HandleAllocator.h",
  	angle_dir .. "src/libANGLE/Image.h",
  	angle_dir .. "src/libANGLE/ImageIndex.h",
  	angle_dir .. "src/libANGLE/IndexRangeCache.h",
  	angle_dir .. "src/libANGLE/InfoLog.h",
  	angle_dir .. "src/libANGLE/LoggingAnnotator.h",
  	angle_dir .. "src/libANGLE/MemoryObject.h",
  	angle_dir .. "src/libANGLE/MemoryProgramCache.h",
  	angle_dir .. "src/libANGLE/Observer.h",
  	angle_dir .. "src/libANGLE/Overlay.cpp",
  	angle_dir .. "src/libANGLE/Overlay.h",
  	angle_dir .. "src/libANGLE/OverlayWidgets.cpp",
  	angle_dir .. "src/libANGLE/OverlayWidgets.h",
  	angle_dir .. "src/libANGLE/Overlay_autogen.cpp",
  	angle_dir .. "src/libANGLE/Overlay_font_autogen.cpp",
  	angle_dir .. "src/libANGLE/Overlay_font_autogen.h",
  	angle_dir .. "src/libANGLE/Program.h",
  	angle_dir .. "src/libANGLE/ProgramExecutable.h",
  	angle_dir .. "src/libANGLE/ProgramLinkedResources.h",
  	angle_dir .. "src/libANGLE/ProgramPipeline.h",
  	angle_dir .. "src/libANGLE/Query.h",
  	angle_dir .. "src/libANGLE/RefCountObject.h",
  	angle_dir .. "src/libANGLE/Renderbuffer.h",
  	angle_dir .. "src/libANGLE/ResourceManager.h",
  	angle_dir .. "src/libANGLE/ResourceMap.h",
  	angle_dir .. "src/libANGLE/Sampler.h",
  	angle_dir .. "src/libANGLE/Semaphore.h",
  	angle_dir .. "src/libANGLE/Shader.h",
  	angle_dir .. "src/libANGLE/SizedMRUCache.h",
  	angle_dir .. "src/libANGLE/State.h",
  	angle_dir .. "src/libANGLE/Stream.h",
  	angle_dir .. "src/libANGLE/Surface.h",
  	angle_dir .. "src/libANGLE/Texture.h",
  	angle_dir .. "src/libANGLE/Thread.h",
  	angle_dir .. "src/libANGLE/TransformFeedback.h",
  	angle_dir .. "src/libANGLE/Uniform.h",
  	angle_dir .. "src/libANGLE/VaryingPacking.h",
  	angle_dir .. "src/libANGLE/Version.h",
  	angle_dir .. "src/libANGLE/Version.inc",
  	angle_dir .. "src/libANGLE/VertexArray.h",
  	angle_dir .. "src/libANGLE/VertexAttribute.h",
  	angle_dir .. "src/libANGLE/VertexAttribute.inc",
  	angle_dir .. "src/libANGLE/WorkerThread.h",
  	angle_dir .. "src/libANGLE/angletypes.h",
  	angle_dir .. "src/libANGLE/angletypes.inc",
  	angle_dir .. "src/libANGLE/entry_points_enum_autogen.h",
  	angle_dir .. "src/libANGLE/entry_points_utils.h",
  	angle_dir .. "src/libANGLE/features.h",
  	angle_dir .. "src/libANGLE/formatutils.h",
  	angle_dir .. "src/libANGLE/histogram_macros.h",
  	angle_dir .. "src/libANGLE/queryconversions.h",
  	angle_dir .. "src/libANGLE/queryutils.h",
  	angle_dir .. "src/libANGLE/trace.h",
  	angle_dir .. "src/libANGLE/renderer/BufferImpl.h",
  	angle_dir .. "src/libANGLE/renderer/CompilerImpl.h",
  	angle_dir .. "src/libANGLE/renderer/ContextImpl.h",
  	angle_dir .. "src/libANGLE/renderer/driver_utils.h",
  	angle_dir .. "src/libANGLE/renderer/DeviceImpl.h",
  	angle_dir .. "src/libANGLE/renderer/DisplayImpl.h",
  	angle_dir .. "src/libANGLE/renderer/EGLImplFactory.h",
  	angle_dir .. "src/libANGLE/renderer/EGLSyncImpl.h",
  	angle_dir .. "src/libANGLE/renderer/FenceNVImpl.h",
  	angle_dir .. "src/libANGLE/renderer/FormatID_autogen.h",
  	angle_dir .. "src/libANGLE/renderer/Format.h",
  	angle_dir .. "src/libANGLE/renderer/FramebufferAttachmentObjectImpl.h",
  	angle_dir .. "src/libANGLE/renderer/FramebufferImpl.h",
  	angle_dir .. "src/libANGLE/renderer/GLImplFactory.h",
  	angle_dir .. "src/libANGLE/renderer/ImageImpl.h",
  	angle_dir .. "src/libANGLE/renderer/MemoryObjectImpl.h",
  	angle_dir .. "src/libANGLE/renderer/OverlayImpl.h",
  	angle_dir .. "src/libANGLE/renderer/ProgramImpl.h",
  	angle_dir .. "src/libANGLE/renderer/ProgramPipelineImpl.h",
  	angle_dir .. "src/libANGLE/renderer/QueryImpl.h",
  	angle_dir .. "src/libANGLE/renderer/RenderbufferImpl.h",
  	angle_dir .. "src/libANGLE/renderer/RenderTargetCache.h",
  	angle_dir .. "src/libANGLE/renderer/SamplerImpl.h",
  	angle_dir .. "src/libANGLE/renderer/SemaphoreImpl.h",
  	angle_dir .. "src/libANGLE/renderer/ShaderImpl.h",
  	angle_dir .. "src/libANGLE/renderer/StreamProducerImpl.h",
  	angle_dir .. "src/libANGLE/renderer/SurfaceImpl.h",
  	angle_dir .. "src/libANGLE/renderer/SyncImpl.h",
  	angle_dir .. "src/libANGLE/renderer/TextureImpl.h",
  	angle_dir .. "src/libANGLE/renderer/TransformFeedbackImpl.h",
  	angle_dir .. "src/libANGLE/renderer/VertexArrayImpl.h",
  	angle_dir .. "src/libANGLE/renderer/copyvertex.h",
  	angle_dir .. "src/libANGLE/renderer/copyvertex.inc.h",
  	angle_dir .. "src/libANGLE/renderer/load_functions_table.h",
  	angle_dir .. "src/libANGLE/renderer/renderer_utils.h",
  	angle_dir .. "src/libANGLE/renderer/serial_utils.h",
  	angle_dir .. "src/libANGLE/validationEGL.h",
  	angle_dir .. "src/libANGLE/validationES.h",
  	angle_dir .. "src/libANGLE/validationES1.h",
  	angle_dir .. "src/libANGLE/validationES1_autogen.h",
  	angle_dir .. "src/libANGLE/validationES2.h",
  	angle_dir .. "src/libANGLE/validationES2_autogen.h",
  	angle_dir .. "src/libANGLE/validationES3.h",
  	angle_dir .. "src/libANGLE/validationES31.h",
  	angle_dir .. "src/libANGLE/validationES31_autogen.h",
  	angle_dir .. "src/libANGLE/validationES32.h",
  	angle_dir .. "src/libANGLE/validationES32_autogen.h",
  	angle_dir .. "src/libANGLE/validationES3_autogen.h",
  	angle_dir .. "src/libANGLE/validationESEXT.h",
  	angle_dir .. "src/libANGLE/validationESEXT_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL11_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL12_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL13_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL14_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL15_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL1_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL21_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL2_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL31_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL32_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL33_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL3_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL41_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL42_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL43_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL44_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL45_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL46_autogen.h",
  	angle_dir .. "src/libANGLE/validationGL4_autogen.h",
  	angle_dir .. "src/third_party/trace_event/trace_event.h",
}

local libangle_sources = {
  	angle_dir .. "src/libANGLE/AttributeMap.cpp",
  	angle_dir .. "src/libANGLE/BlobCache.cpp",
  	angle_dir .. "src/libANGLE/Buffer.cpp",
  	angle_dir .. "src/libANGLE/Caps.cpp",
  	angle_dir .. "src/libANGLE/Compiler.cpp",
  	angle_dir .. "src/libANGLE/Config.cpp",
  	angle_dir .. "src/libANGLE/Context.cpp",
  	angle_dir .. "src/libANGLE/Context_gl.cpp",
  	angle_dir .. "src/libANGLE/Context_gles_1_0.cpp",
  	angle_dir .. "src/libANGLE/Debug.cpp",
  	angle_dir .. "src/libANGLE/Device.cpp",
  	angle_dir .. "src/libANGLE/Display.cpp",
  	angle_dir .. "src/libANGLE/EGLSync.cpp",
  	angle_dir .. "src/libANGLE/Error.cpp",
  	angle_dir .. "src/libANGLE/Fence.cpp",
  	angle_dir .. "src/libANGLE/Framebuffer.cpp",
  	angle_dir .. "src/libANGLE/FramebufferAttachment.cpp",
  	angle_dir .. "src/libANGLE/GLES1Renderer.cpp",
  	angle_dir .. "src/libANGLE/GLES1State.cpp",
  	angle_dir .. "src/libANGLE/HandleAllocator.cpp",
  	angle_dir .. "src/libANGLE/Image.cpp",
  	angle_dir .. "src/libANGLE/ImageIndex.cpp",
  	angle_dir .. "src/libANGLE/IndexRangeCache.cpp",
  	angle_dir .. "src/libANGLE/LoggingAnnotator.cpp",
  	angle_dir .. "src/libANGLE/MemoryObject.cpp",
  	angle_dir .. "src/libANGLE/MemoryProgramCache.cpp",
  	angle_dir .. "src/libANGLE/Observer.cpp",
  	angle_dir .. "src/libANGLE/Platform.cpp",
  	angle_dir .. "src/libANGLE/Program.cpp",
  	angle_dir .. "src/libANGLE/ProgramExecutable.cpp",
  	angle_dir .. "src/libANGLE/ProgramLinkedResources.cpp",
  	angle_dir .. "src/libANGLE/ProgramPipeline.cpp",
  	angle_dir .. "src/libANGLE/Query.cpp",
  	angle_dir .. "src/libANGLE/Renderbuffer.cpp",
  	angle_dir .. "src/libANGLE/ResourceManager.cpp",
  	angle_dir .. "src/libANGLE/Sampler.cpp",
  	angle_dir .. "src/libANGLE/Semaphore.cpp",
  	angle_dir .. "src/libANGLE/Shader.cpp",
  	angle_dir .. "src/libANGLE/State.cpp",
  	angle_dir .. "src/libANGLE/Stream.cpp",
  	angle_dir .. "src/libANGLE/Surface.cpp",
  	angle_dir .. "src/libANGLE/Texture.cpp",
  	angle_dir .. "src/libANGLE/Thread.cpp",
  	angle_dir .. "src/libANGLE/TransformFeedback.cpp",
  	angle_dir .. "src/libANGLE/Uniform.cpp",
  	angle_dir .. "src/libANGLE/VaryingPacking.cpp",
  	angle_dir .. "src/libANGLE/VertexArray.cpp",
  	angle_dir .. "src/libANGLE/VertexAttribute.cpp",
  	angle_dir .. "src/libANGLE/WorkerThread.cpp",
  	angle_dir .. "src/libANGLE/angletypes.cpp",
  	angle_dir .. "src/libANGLE/entry_points_enum_autogen.cpp",
  	angle_dir .. "src/libANGLE/es3_copy_conversion_table_autogen.cpp",
  	angle_dir .. "src/libANGLE/format_map_autogen.cpp",
  	angle_dir .. "src/libANGLE/format_map_desktop.cpp",
  	angle_dir .. "src/libANGLE/formatutils.cpp",
  	angle_dir .. "src/libANGLE/queryconversions.cpp",
  	angle_dir .. "src/libANGLE/queryutils.cpp",
  	angle_dir .. "src/libANGLE/renderer/ContextImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/DeviceImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/DisplayImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/Format_table_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/QueryImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/ShaderImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/SurfaceImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/TextureImpl.cpp",
  	angle_dir .. "src/libANGLE/renderer/driver_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/load_functions_table_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/renderer_utils.cpp",
  	angle_dir .. "src/libANGLE/validationEGL.cpp",
  	angle_dir .. "src/libANGLE/validationES.cpp",
  	angle_dir .. "src/libANGLE/validationES1.cpp",
  	angle_dir .. "src/libANGLE/validationES2.cpp",
  	angle_dir .. "src/libANGLE/validationES3.cpp",
  	angle_dir .. "src/libANGLE/validationES31.cpp",
  	angle_dir .. "src/libANGLE/validationES32.cpp",
  	angle_dir .. "src/libANGLE/validationESEXT.cpp",
  	angle_dir .. "src/libANGLE/validationGL1.cpp",
  	angle_dir .. "src/libANGLE/validationGL11.cpp",
  	angle_dir .. "src/libANGLE/validationGL12.cpp",
  	angle_dir .. "src/libANGLE/validationGL13.cpp",
  	angle_dir .. "src/libANGLE/validationGL14.cpp",
  	angle_dir .. "src/libANGLE/validationGL15.cpp",
  	angle_dir .. "src/libANGLE/validationGL2.cpp",
  	angle_dir .. "src/libANGLE/validationGL21.cpp",
  	angle_dir .. "src/libANGLE/validationGL3.cpp",
  	angle_dir .. "src/libANGLE/validationGL31.cpp",
  	angle_dir .. "src/libANGLE/validationGL32.cpp",
  	angle_dir .. "src/libANGLE/validationGL33.cpp",
  	angle_dir .. "src/libANGLE/validationGL4.cpp",
  	angle_dir .. "src/libANGLE/validationGL41.cpp",
  	angle_dir .. "src/libANGLE/validationGL42.cpp",
  	angle_dir .. "src/libANGLE/validationGL43.cpp",
  	angle_dir .. "src/libANGLE/validationGL44.cpp",
  	angle_dir .. "src/libANGLE/validationGL45.cpp",
  	angle_dir .. "src/libANGLE/validationGL46.cpp",
	angle_dir .. "src/libANGLE/FrameCapture.h",
	angle_dir .. "src/libANGLE/capture_gles_1_0_autogen.h",
	angle_dir .. "src/libANGLE/capture_gles_2_0_autogen.h",
	angle_dir .. "src/libANGLE/capture_gles_3_0_autogen.h",
	angle_dir .. "src/libANGLE/capture_gles_3_1_autogen.h",
	angle_dir .. "src/libANGLE/capture_gles_3_2_autogen.h",
	angle_dir .. "src/libANGLE/capture_gles_ext_autogen.h",
	angle_dir .. "src/libANGLE/frame_capture_utils_autogen.h",
	angle_dir .. "src/libANGLE/gl_enum_utils.h",
	angle_dir .. "src/libANGLE/gl_enum_utils_autogen.h",
}

local libangle_d3d_shared_sources = {
  	angle_dir .. "src/libANGLE/renderer/d3d/BufferD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/BufferD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/CompilerD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/CompilerD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/ContextD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/DeviceD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/DeviceD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/DisplayD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/DisplayD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/DynamicHLSL.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/DynamicHLSL.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/DynamicImage2DHLSL.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/DynamicImage2DHLSL.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/EGLImageD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/EGLImageD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/FramebufferD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/FramebufferD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/HLSLCompiler.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/HLSLCompiler.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/ImageD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/ImageD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/IndexBuffer.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/IndexBuffer.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/IndexDataManager.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/IndexDataManager.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/NativeWindowD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/NativeWindowD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/ProgramD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/ProgramD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/RenderTargetD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/RenderTargetD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/RenderbufferD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/RenderbufferD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/RendererD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/RendererD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/SamplerD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/ShaderD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/ShaderD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/ShaderExecutableD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/ShaderExecutableD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/SurfaceD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/SurfaceD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/SwapChainD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/SwapChainD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/TextureD3D.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/TextureD3D.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/TextureStorage.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/VertexBuffer.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/VertexBuffer.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/VertexDataManager.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/VertexDataManager.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/formatutilsD3D.h",
}

local libangle_d3d9_sources = {
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Blit9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Blit9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Buffer9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Buffer9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Context9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Context9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/DebugAnnotator9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/DebugAnnotator9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Fence9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Fence9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Framebuffer9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Framebuffer9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Image9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Image9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/IndexBuffer9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/IndexBuffer9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/NativeWindow9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/NativeWindow9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Query9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Query9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/RenderTarget9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/RenderTarget9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Renderer9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/Renderer9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/ShaderCache.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/ShaderExecutable9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/ShaderExecutable9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/StateManager9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/StateManager9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/SwapChain9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/SwapChain9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/TextureStorage9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/TextureStorage9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/VertexArray9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/VertexBuffer9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/VertexBuffer9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/VertexDeclarationCache.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/VertexDeclarationCache.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/formatutils9.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/formatutils9.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/renderer9_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/renderer9_utils.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskpremultps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskunmultps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminancepremultps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminanceps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminanceunmultps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/passthroughps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/shaders/compiled/standardvs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d9/vertexconversion.h",
}

local libangle_d3d11_sources = {
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Blit11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Blit11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Blit11Helper_autogen.inc",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Buffer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Buffer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Clear11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Clear11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Context11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Context11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/DebugAnnotator11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/DebugAnnotator11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ExternalImageSiblingImpl11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ExternalImageSiblingImpl11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Fence11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Fence11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Framebuffer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Framebuffer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Image11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Image11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/IndexBuffer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/IndexBuffer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/InputLayoutCache.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/InputLayoutCache.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/MappedSubresourceVerifier11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/MappedSubresourceVerifier11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/NativeWindow11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/PixelTransfer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/PixelTransfer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Program11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Program11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ProgramPipeline11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ProgramPipeline11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Query11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Query11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/RenderStateCache.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/RenderStateCache.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/RenderTarget11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/RenderTarget11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Renderer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Renderer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ResourceManager11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ResourceManager11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ShaderExecutable11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/ShaderExecutable11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/StateManager11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/StateManager11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/StreamProducerD3DTexture.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/StreamProducerD3DTexture.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/SwapChain11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/SwapChain11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/TextureStorage11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/TextureStorage11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/TransformFeedback11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/TransformFeedback11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Trim11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/Trim11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/VertexArray11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/VertexArray11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/VertexBuffer11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/VertexBuffer11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/dxgi_format_map_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/dxgi_support_table.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/dxgi_support_table_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/formatutils11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/renderer11_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/renderer11_utils.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_gs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4f.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4i.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4ui.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11_fl9vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11multiviewgs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11multiviewvs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/cleardepth11ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11_fl9ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps1.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps2.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps3.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps4.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps5.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps6.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps7.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps8.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps1.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps2.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps3.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps4.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps5.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps6.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps7.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps8.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps1.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps2.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps3.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps4.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps5.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps6.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps7.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps8.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough2d11vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough3d11gs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough3d11vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthroughdepth2d11ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthroughrgba2dms11ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvecolor2dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepth11_ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepthstencil11_ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepthstencil11_vs.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvestencil11_ps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef2darrayps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef2dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef3dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei2darrayps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei2dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei3dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui2darrayps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui2dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui3dps.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/texture_format_table.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/texture_format_table.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/texture_format_table_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/texture_format_table_utils.h",
}

local libangle_d3d11_win32_sources = {
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/converged/CompositorNativeWindow11.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/converged/CompositorNativeWindow11.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/win32/NativeWindow11Win32.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/win32/NativeWindow11Win32.h",
  	angle_dir .. "src/third_party/systeminfo/SystemInfo.cpp",
  	angle_dir .. "src/third_party/systeminfo/SystemInfo.h",
}

local libangle_d3d11_winuwp_sources = {
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/InspectableNativeWindow.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/InspectableNativeWindow.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/NativeWindow11WinRT.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/NativeWindow11WinRT.h",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/SwapChainPanelNativeWindow.cpp",
  	angle_dir .. "src/libANGLE/renderer/d3d/d3d11/winrt/SwapChainPanelNativeWindow.h",
}

local libangle_gl_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/BlitGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/BlitGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/BufferGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/BufferGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ClearMultiviewGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ClearMultiviewGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/CompilerGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/CompilerGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ContextGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ContextGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/DispatchTableGL_autogen.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/DispatchTableGL_autogen.h",
  	angle_dir .. "src/libANGLE/renderer/gl/DisplayGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/DisplayGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/FenceNVGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/FenceNVGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/FramebufferGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/FramebufferGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/FunctionsGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/FunctionsGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ImageGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ImageGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/MemoryObjectGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/MemoryObjectGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ProgramGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ProgramGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ProgramPipelineGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ProgramPipelineGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/QueryGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/QueryGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/RenderbufferGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/RenderbufferGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/RendererGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/RendererGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/SamplerGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/SamplerGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/SemaphoreGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/SemaphoreGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/ShaderGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/ShaderGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/StateManagerGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/StateManagerGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/SurfaceGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/SurfaceGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/SyncGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/SyncGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/TextureGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/TextureGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/TransformFeedbackGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/TransformFeedbackGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/VertexArrayGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/VertexArrayGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/formatutilsgl.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/formatutilsgl.h",
  	angle_dir .. "src/libANGLE/renderer/gl/functionsgl_enums.h",
  	angle_dir .. "src/libANGLE/renderer/gl/functionsgl_typedefs.h",
  	angle_dir .. "src/libANGLE/renderer/gl/renderergl_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/renderergl_utils.h",
}

local libangle_gl_null_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/null_functions.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/null_functions.h",
}

local libangle_gl_wgl_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/ContextWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/ContextWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/D3DTextureSurfaceWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/D3DTextureSurfaceWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/DXGISwapChainWindowSurfaceWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/DXGISwapChainWindowSurfaceWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/DisplayWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/DisplayWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/FunctionsWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/FunctionsWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/PbufferSurfaceWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/PbufferSurfaceWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/RendererWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/RendererWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/SurfaceWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/WindowSurfaceWGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/WindowSurfaceWGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/functionswgl_typedefs.h",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/wgl_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/wgl/wgl_utils.h",
  	angle_dir .. "src/third_party/khronos/GL/wglext.h",
}

local libangle_gl_glx_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/glx/DisplayGLX.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/DisplayGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/FunctionsGLX.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/FunctionsGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/PbufferSurfaceGLX.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/PbufferSurfaceGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/RendererGLX.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/RendererGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/SurfaceGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/WindowSurfaceGLX.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/WindowSurfaceGLX.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/functionsglx_typedefs.h",
  	angle_dir .. "src/libANGLE/renderer/gl/glx/platform_glx.h",
}

local libangle_gl_egl_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ContextEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ContextEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/DisplayEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/DisplayEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ExternalImageSiblingEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/FunctionsEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/FunctionsEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ImageEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ImageEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/PbufferSurfaceEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/PbufferSurfaceEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/RendererEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/RendererEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/SurfaceEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/SurfaceEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/SyncEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/SyncEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/WindowSurfaceEGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/WindowSurfaceEGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/egl_utils.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/egl_utils.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/functionsegl_typedefs.h",
}

local libangle_gl_egl_dl_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/egl/FunctionsEGLDL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/FunctionsEGLDL.h",
}

local libangle_gl_ozone_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ozone/DisplayOzone.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ozone/DisplayOzone.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ozone/SurfaceOzone.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/ozone/SurfaceOzone.h",
}

local libangle_gl_egl_android_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/egl/android/DisplayAndroid.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/android/DisplayAndroid.h",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/android/NativeBufferImageSiblingAndroid.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/egl/android/NativeBufferImageSiblingAndroid.h",
}

local libangle_gl_cgl_sources = {
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/ContextCGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/ContextCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/DeviceCGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/DeviceCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/DisplayCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/DisplayCGL.mm",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/IOSurfaceSurfaceCGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/IOSurfaceSurfaceCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/PbufferSurfaceCGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/PbufferSurfaceCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/RendererCGL.cpp",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/RendererCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.h",
  	angle_dir .. "src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm",
}

local libangle_mac_sources = { angle_dir .. "src/libANGLE/renderer/driver_utils_mac.mm" }

-- The frame capture headers are always visible to libANGLE.

local libangle_capture_sources = {
  	-- angle_dir .. "src/libANGLE/FrameCapture.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_1_0_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_1_0_params.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_2_0_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_2_0_params.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_0_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_0_params.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_1_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_1_params.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_2_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_3_2_params.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_ext_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/capture_gles_ext_params.cpp",
  	-- angle_dir .. "src/libANGLE/frame_capture_replay_autogen.cpp",
  	-- angle_dir .. "src/libANGLE/frame_capture_utils_autogen.cpp",
  	angle_dir .. "src/libANGLE/gl_enum_utils.cpp",
  	angle_dir .. "src/libANGLE/gl_enum_utils_autogen.cpp",
}

local libangle_null_sources = {
  	angle_dir .. "src/libANGLE/renderer/null/BufferNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/BufferNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/CompilerNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/CompilerNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/ContextNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/ContextNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/DeviceNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/DeviceNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/DisplayNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/DisplayNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/FenceNVNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/FenceNVNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/FramebufferNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/FramebufferNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/ImageNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/ImageNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/ProgramNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/ProgramNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/ProgramPipelineNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/ProgramPipelineNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/QueryNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/QueryNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/RenderbufferNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/RenderbufferNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/SamplerNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/SamplerNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/ShaderNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/ShaderNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/SurfaceNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/SurfaceNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/SyncNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/SyncNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/TextureNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/TextureNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/TransformFeedbackNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/TransformFeedbackNULL.h",
  	angle_dir .. "src/libANGLE/renderer/null/VertexArrayNULL.cpp",
  	angle_dir .. "src/libANGLE/renderer/null/VertexArrayNULL.h",
}

local libgl_sources = {
  	angle_dir .. "src/common/angleutils.h",
  	angle_dir .. "src/common/debug.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_0_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_0_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_1_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_1_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_2_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_2_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_3_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_3_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_4_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_4_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_1_5_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_1_5_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_2_0_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_2_0_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_2_1_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_2_1_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_3_0_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_3_0_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_3_1_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_3_1_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_3_2_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_3_2_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_3_3_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_3_3_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_0_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_0_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_1_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_1_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_2_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_2_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_3_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_3_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_4_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_4_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_5_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_5_autogen.h",
  	angle_dir .. "src/libGL/entry_points_gl_4_6_autogen.cpp",
  	angle_dir .. "src/libGL/entry_points_gl_4_6_autogen.h",
  	angle_dir .. "src/libGL/entry_points_wgl.cpp",
  	angle_dir .. "src/libGL/entry_points_wgl.h",
  	angle_dir .. "src/libGL/libGL.rc",
  	angle_dir .. "src/libGL/libGL_autogen.cpp",
  	angle_dir .. "src/libGL/libGL_autogen.def",
  	angle_dir .. "src/libGL/proc_table_wgl.h",
  	angle_dir .. "src/libGL/proc_table_wgl_autogen.cpp",
  	angle_dir .. "src/libGLESv2/global_state.cpp",
  	angle_dir .. "src/libGLESv2/global_state.h",
  	angle_dir .. "src/libGLESv2/resource.h",
}

local libglesv2_sources = {
  	angle_dir .. "src/common/angleutils.h",
  	angle_dir .. "src/common/debug.h",
  	angle_dir .. "src/libANGLE/entry_points_enum_autogen.h",
  	angle_dir .. "src/libANGLE/entry_points_utils.h",
  	angle_dir .. "src/libGLESv2/entry_points_egl.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_egl.h",
  	angle_dir .. "src/libGLESv2/entry_points_egl_ext.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_egl_ext.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_1_0_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_1_0_autogen.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_2_0_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_2_0_autogen.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_0_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_0_autogen.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_1_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_1_autogen.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_2_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_3_2_autogen.h",
  	angle_dir .. "src/libGLESv2/entry_points_gles_ext_autogen.cpp",
  	angle_dir .. "src/libGLESv2/entry_points_gles_ext_autogen.h",
  	angle_dir .. "src/libGLESv2/global_state.cpp",
  	angle_dir .. "src/libGLESv2/global_state.h",
  	angle_dir .. "src/libGLESv2/libGLESv2.rc",
  	angle_dir .. "src/libGLESv2/libGLESv2_autogen.cpp",
  	angle_dir .. "src/libGLESv2/proc_table_egl.h",
  	angle_dir .. "src/libGLESv2/proc_table_egl_autogen.cpp",
  	angle_dir .. "src/libGLESv2/resource.h",
}

local libglesv1_cm_sources = {
  	angle_dir .. "src/libGLESv1_CM/libGLESv1_CM.cpp",
  	angle_dir .. "src/libGLESv1_CM/libGLESv1_CM.def",
  	angle_dir .. "src/libGLESv1_CM/libGLESv1_CM.rc",
  	angle_dir .. "src/libGLESv1_CM/resource.h",
}

local libegl_sources = {
  	angle_dir .. "src/libEGL/egl_loader_autogen.h",
  	angle_dir .. "src/libEGL/libEGL.cpp",
  	angle_dir .. "src/libEGL/libEGL.rc",
  	angle_dir .. "src/libEGL/resource.h",
  	angle_dir .. "src/libGLESv2/entry_points_egl.h",
  	angle_dir .. "src/libGLESv2/entry_points_egl_ext.h",
}

local no_gl_prototypes = {
    "GL_GLES_PROTOTYPES=0",
    "EGL_EGL_PROTOTYPES=0",
}

local gl_prototypes = {
	"GL_GLES_PROTOTYPES=1",
	"EGL_EGL_PROTOTYPES=1",
	"GL_GLEXT_PROTOTYPES",
	"EGL_EGLEXT_PROTOTYPES",
}

local global_defines = {
	'ANGLE_EGL_LIBRARY_NAME=\\"libEGL\\"',
	"ANGLE_GENERATE_SHADER_DEBUG_INFO",
	"USE_UDEV -DUSE_AURA=1",
	"USE_GLIB=1",
	"USE_NSS_CERTS=1",
	"USE_X11=1",
	"_FILE_OFFSET_BITS=64",
	"_LARGEFILE_SOURCE",
	"_LARGEFILE64_SOURCE",
	"_GNU_SOURCE",
	"__STDC_CONSTANT_MACROS",
	"__STDC_FORMAT_MACROS",
	"COMPONENT_BUILD",
	"_DEBUG",
	"DYNAMIC_ANNOTATIONS_ENABLED=1",
	"ANGLE_IS_64_BIT_CPU",
	"ANGLE_ENABLE_DEBUG_ANNOTATIONS",
	"LIBANGLE_IMPLEMENTATION",
	"ANGLE_USE_X11",
	"ANGLE_ENABLE_OPENGL",
	"ANGLE_ENABLE_OPENGL_NULL",
	"ANGLE_ENABLE_NULL",
	{ "ANGLE_USE_X11"; Config = "linux-*-*" },
	"ANGLE_ENABLE_NULL",
	"_CRT_SECURE_NO_DEPRECATE",
	"_SCL_SECURE_NO_WARNINGS",
	"_HAS_EXCEPTIONS=0",
	"NOMINMAX",
	-- TODO: Change this for actually replay target, on PC we assume 64-bit
	"ANGLE_IS_64_BIT_CPU",
}

local angle_translator_exported_headers = {
	angle_dir .. "include/GLSLANG/ShaderLang.h",
	angle_dir .. "include/GLSLANG/ShaderVars.h",
	angle_dir .. "src/compiler/translator/blocklayout.h",
	angle_dir .. "src/compiler/translator/blocklayoutHLSL.h",
}

local angle_translator_sources = {
	angle_dir .. "include/EGL/egl.h",
	angle_dir .. "include/EGL/eglext.h",
	angle_dir .. "include/EGL/eglplatform.h",
	angle_dir .. "include/GLES2/gl2.h",
	angle_dir .. "include/GLES2/gl2ext.h",
	angle_dir .. "include/GLES2/gl2platform.h",
	angle_dir .. "include/GLES3/gl3.h",
	angle_dir .. "include/GLES3/gl31.h",
	angle_dir .. "include/GLES3/gl32.h",
	angle_dir .. "include/GLES3/gl3platform.h",
	angle_dir .. "include/KHR/khrplatform.h",
	angle_dir .. "include/angle_gl.h",
	angle_dir .. "src/compiler/translator/BaseTypes.h",
	angle_dir .. "src/compiler/translator/BuiltInFunctionEmulator.cpp",
	angle_dir .. "src/compiler/translator/BuiltInFunctionEmulator.h",
	angle_dir .. "src/compiler/translator/CallDAG.cpp",
	angle_dir .. "src/compiler/translator/CallDAG.h",
	angle_dir .. "src/compiler/translator/CodeGen.cpp",
	angle_dir .. "src/compiler/translator/CollectVariables.cpp",
	angle_dir .. "src/compiler/translator/CollectVariables.h",
	angle_dir .. "src/compiler/translator/Common.h",
	angle_dir .. "src/compiler/translator/Compiler.cpp",
	angle_dir .. "src/compiler/translator/Compiler.h",
	angle_dir .. "src/compiler/translator/ConstantUnion.cpp",
	angle_dir .. "src/compiler/translator/ConstantUnion.h",
	angle_dir .. "src/compiler/translator/Declarator.cpp",
	angle_dir .. "src/compiler/translator/Declarator.h",
	angle_dir .. "src/compiler/translator/Diagnostics.cpp",
	angle_dir .. "src/compiler/translator/Diagnostics.h",
	angle_dir .. "src/compiler/translator/DirectiveHandler.cpp",
	angle_dir .. "src/compiler/translator/DirectiveHandler.h",
	angle_dir .. "src/compiler/translator/ExtensionBehavior.cpp",
	angle_dir .. "src/compiler/translator/ExtensionBehavior.h",
	angle_dir .. "src/compiler/translator/FlagStd140Structs.cpp",
	angle_dir .. "src/compiler/translator/FlagStd140Structs.h",
	angle_dir .. "src/compiler/translator/FunctionLookup.cpp",
	angle_dir .. "src/compiler/translator/FunctionLookup.h",
	angle_dir .. "src/compiler/translator/HashNames.cpp",
	angle_dir .. "src/compiler/translator/HashNames.h",
	angle_dir .. "src/compiler/translator/ImmutableString.h",
	angle_dir .. "src/compiler/translator/ImmutableStringBuilder.cpp",
	angle_dir .. "src/compiler/translator/ImmutableStringBuilder.h",
	angle_dir .. "src/compiler/translator/InfoSink.cpp",
	angle_dir .. "src/compiler/translator/InfoSink.h",
	angle_dir .. "src/compiler/translator/Initialize.cpp",
	angle_dir .. "src/compiler/translator/Initialize.h",
	angle_dir .. "src/compiler/translator/InitializeDll.cpp",
	angle_dir .. "src/compiler/translator/InitializeDll.h",
	angle_dir .. "src/compiler/translator/InitializeGlobals.h",
	angle_dir .. "src/compiler/translator/IntermNode.cpp",
	angle_dir .. "src/compiler/translator/IntermNode.h",
	angle_dir .. "src/compiler/translator/IsASTDepthBelowLimit.cpp",
	angle_dir .. "src/compiler/translator/IsASTDepthBelowLimit.h",
	angle_dir .. "src/compiler/translator/Operator.cpp",
	angle_dir .. "src/compiler/translator/Operator.h",
	angle_dir .. "src/compiler/translator/OutputTree.cpp",
	angle_dir .. "src/compiler/translator/OutputTree.h",
	angle_dir .. "src/compiler/translator/ParseContext.cpp",
	angle_dir .. "src/compiler/translator/ParseContext.h",
	angle_dir .. "src/compiler/translator/ParseContext_ESSL_autogen.h",
	angle_dir .. "src/compiler/translator/ParseContext_complete_autogen.h",
	angle_dir .. "src/compiler/translator/ParseContext_interm.h",
	angle_dir .. "src/compiler/translator/PoolAlloc.cpp",
	angle_dir .. "src/compiler/translator/PoolAlloc.h",
	angle_dir .. "src/compiler/translator/Pragma.h",
	angle_dir .. "src/compiler/translator/QualifierTypes.cpp",
	angle_dir .. "src/compiler/translator/QualifierTypes.h",
	angle_dir .. "src/compiler/translator/Severity.h",
	angle_dir .. "src/compiler/translator/ShaderLang.cpp",
	angle_dir .. "src/compiler/translator/ShaderVars.cpp",
	angle_dir .. "src/compiler/translator/StaticType.h",
	angle_dir .. "src/compiler/translator/Symbol.cpp",
	angle_dir .. "src/compiler/translator/Symbol.h",
	angle_dir .. "src/compiler/translator/SymbolTable.cpp",
	angle_dir .. "src/compiler/translator/SymbolTable.h",
	angle_dir .. "src/compiler/translator/SymbolTable_autogen.h",
	angle_dir .. "src/compiler/translator/SymbolUniqueId.cpp",
	angle_dir .. "src/compiler/translator/SymbolUniqueId.h",
	angle_dir .. "src/compiler/translator/Types.cpp",
	angle_dir .. "src/compiler/translator/Types.h",
	angle_dir .. "src/compiler/translator/ValidateAST.cpp",
	angle_dir .. "src/compiler/translator/ValidateAST.h",
	angle_dir .. "src/compiler/translator/ValidateGlobalInitializer.cpp",
	angle_dir .. "src/compiler/translator/ValidateGlobalInitializer.h",
	angle_dir .. "src/compiler/translator/ValidateLimitations.cpp",
	angle_dir .. "src/compiler/translator/ValidateLimitations.h",
	angle_dir .. "src/compiler/translator/ValidateMaxParameters.cpp",
	angle_dir .. "src/compiler/translator/ValidateMaxParameters.h",
	angle_dir .. "src/compiler/translator/ValidateOutputs.cpp",
	angle_dir .. "src/compiler/translator/ValidateOutputs.h",
	angle_dir .. "src/compiler/translator/ValidateSwitch.cpp",
	angle_dir .. "src/compiler/translator/ValidateSwitch.h",
	angle_dir .. "src/compiler/translator/ValidateVaryingLocations.cpp",
	angle_dir .. "src/compiler/translator/ValidateVaryingLocations.h",
	angle_dir .. "src/compiler/translator/VariablePacker.cpp",
	angle_dir .. "src/compiler/translator/VariablePacker.h",
	angle_dir .. "src/compiler/translator/blocklayout.cpp",
	angle_dir .. "src/compiler/translator/glslang.h",
	angle_dir .. "src/compiler/translator/glslang_lex_autogen.cpp",
	angle_dir .. "src/compiler/translator/glslang_tab_autogen.cpp",
	angle_dir .. "src/compiler/translator/glslang_tab_autogen.h",
	angle_dir .. "src/compiler/translator/length_limits.h",
	angle_dir .. "src/compiler/translator/tree_ops/AddAndTrueToLoopCondition.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/AddAndTrueToLoopCondition.h",
	angle_dir .. "src/compiler/translator/tree_ops/BreakVariableAliasingInInnerLoops.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/BreakVariableAliasingInInnerLoops.h",
	angle_dir .. "src/compiler/translator/tree_ops/ClampFragDepth.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/ClampFragDepth.h",
	angle_dir .. "src/compiler/translator/tree_ops/ClampPointSize.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/ClampPointSize.h",
	angle_dir .. "src/compiler/translator/tree_ops/DeclareAndInitBuiltinsForInstancedMultiview.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/DeclareAndInitBuiltinsForInstancedMultiview.h",
	angle_dir .. "src/compiler/translator/tree_ops/DeferGlobalInitializers.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/DeferGlobalInitializers.h",
	angle_dir .. "src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.h",
	angle_dir .. "src/compiler/translator/tree_ops/EmulateMultiDrawShaderBuiltins.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/EmulateMultiDrawShaderBuiltins.h",
	angle_dir .. "src/compiler/translator/tree_ops/EmulatePrecision.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/EmulatePrecision.h",
	angle_dir .. "src/compiler/translator/tree_ops/ExpandIntegerPowExpressions.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/ExpandIntegerPowExpressions.h",
	angle_dir .. "src/compiler/translator/tree_ops/FoldExpressions.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/FoldExpressions.h",
	angle_dir .. "src/compiler/translator/tree_ops/InitializeVariables.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/InitializeVariables.h",
	angle_dir .. "src/compiler/translator/tree_ops/NameEmbeddedUniformStructs.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/NameEmbeddedUniformStructs.h",
	angle_dir .. "src/compiler/translator/tree_ops/PruneEmptyCases.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/PruneEmptyCases.h",
	angle_dir .. "src/compiler/translator/tree_ops/PruneNoOps.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/PruneNoOps.h",
	angle_dir .. "src/compiler/translator/tree_ops/RecordConstantPrecision.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RecordConstantPrecision.h",
	angle_dir .. "src/compiler/translator/tree_ops/RegenerateStructNames.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RegenerateStructNames.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveArrayLengthMethod.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveArrayLengthMethod.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveAtomicCounterBuiltins.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveAtomicCounterBuiltins.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveDynamicIndexing.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveDynamicIndexing.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveInactiveInterfaceVariables.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveInactiveInterfaceVariables.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveInvariantDeclaration.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveInvariantDeclaration.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemovePow.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemovePow.h",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveUnreferencedVariables.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RemoveUnreferencedVariables.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteAtomicCounters.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteAtomicCounters.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteAtomicFunctionExpressions.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteAtomicFunctionExpressions.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteCubeMapSamplersAs2DArray.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteCubeMapSamplersAs2DArray.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteDfdy.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteDfdy.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteDoWhile.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteDoWhile.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteExpressionsWithShaderStorageBlock.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteExpressionsWithShaderStorageBlock.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteRepeatedAssignToSwizzled.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteRepeatedAssignToSwizzled.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteRowMajorMatrices.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteRowMajorMatrices.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteStructSamplers.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteStructSamplers.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteStructSamplersOld.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteTexelFetchOffset.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteTexelFetchOffset.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteUnaryMinusOperatorFloat.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteUnaryMinusOperatorFloat.h",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteUnaryMinusOperatorInt.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/RewriteUnaryMinusOperatorInt.h",
	angle_dir .. "src/compiler/translator/tree_ops/ScalarizeVecAndMatConstructorArgs.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/ScalarizeVecAndMatConstructorArgs.h",
	angle_dir .. "src/compiler/translator/tree_ops/SeparateDeclarations.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/SeparateDeclarations.h",
	angle_dir .. "src/compiler/translator/tree_ops/SimplifyLoopConditions.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/SimplifyLoopConditions.h",
	angle_dir .. "src/compiler/translator/tree_ops/SplitSequenceOperator.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/SplitSequenceOperator.h",
	angle_dir .. "src/compiler/translator/tree_ops/UnfoldShortCircuitAST.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/UnfoldShortCircuitAST.h",
	angle_dir .. "src/compiler/translator/tree_ops/UseInterfaceBlockFields.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/UseInterfaceBlockFields.h",
	angle_dir .. "src/compiler/translator/tree_ops/VectorizeVectorScalarArithmetic.cpp",
	angle_dir .. "src/compiler/translator/tree_ops/VectorizeVectorScalarArithmetic.h",
	angle_dir .. "src/compiler/translator/tree_util/BuiltIn.h",
	angle_dir .. "src/compiler/translator/tree_util/BuiltIn_ESSL_autogen.h",
	angle_dir .. "src/compiler/translator/tree_util/BuiltIn_complete_autogen.h",
	angle_dir .. "src/compiler/translator/tree_util/FindFunction.cpp",
	angle_dir .. "src/compiler/translator/tree_util/FindFunction.h",
	angle_dir .. "src/compiler/translator/tree_util/FindMain.cpp",
	angle_dir .. "src/compiler/translator/tree_util/FindMain.h",
	angle_dir .. "src/compiler/translator/tree_util/FindSymbolNode.cpp",
	angle_dir .. "src/compiler/translator/tree_util/FindSymbolNode.h",
	angle_dir .. "src/compiler/translator/tree_util/IntermNodePatternMatcher.cpp",
	angle_dir .. "src/compiler/translator/tree_util/IntermNodePatternMatcher.h",
	angle_dir .. "src/compiler/translator/tree_util/IntermNode_util.cpp",
	angle_dir .. "src/compiler/translator/tree_util/IntermNode_util.h",
	angle_dir .. "src/compiler/translator/tree_util/IntermTraverse.cpp",
	angle_dir .. "src/compiler/translator/tree_util/IntermTraverse.h",
	angle_dir .. "src/compiler/translator/tree_util/NodeSearch.h",
	angle_dir .. "src/compiler/translator/tree_util/ReplaceShadowingVariables.cpp",
	angle_dir .. "src/compiler/translator/tree_util/ReplaceShadowingVariables.h",
	angle_dir .. "src/compiler/translator/tree_util/ReplaceVariable.cpp",
	angle_dir .. "src/compiler/translator/tree_util/ReplaceVariable.h",
	angle_dir .. "src/compiler/translator/tree_util/RunAtTheEndOfShader.cpp",
	angle_dir .. "src/compiler/translator/tree_util/RunAtTheEndOfShader.h",
	angle_dir .. "src/compiler/translator/tree_util/Visit.h",
	angle_dir .. "src/compiler/translator/util.cpp",
	angle_dir .. "src/compiler/translator/util.h",
	angle_dir .. "src/compiler/translator/ImmutableString_autogen.cpp",
	angle_dir .. "src/compiler/translator/SymbolTable_autogen.cpp",
	angle_dir .. "src/third_party/compiler/ArrayBoundsClamper.cpp",
	angle_dir .. "src/third_party/compiler/ArrayBoundsClamper.h",
}

local angle_translator_essl_sources = {
	angle_dir .. "src/compiler/translator/OutputESSL.cpp",
	angle_dir .. "src/compiler/translator/OutputESSL.h",
	angle_dir .. "src/compiler/translator/TranslatorESSL.cpp",
	angle_dir .. "src/compiler/translator/TranslatorESSL.h",
}

local angle_translator_glsl_sources = {
	angle_dir .. "src/compiler/translator/BuiltInFunctionEmulatorGLSL.cpp",
	angle_dir .. "src/compiler/translator/BuiltInFunctionEmulatorGLSL.h",
	angle_dir .. "src/compiler/translator/BuiltinsWorkaroundGLSL.cpp",
	angle_dir .. "src/compiler/translator/BuiltinsWorkaroundGLSL.h",
	angle_dir .. "src/compiler/translator/ExtensionGLSL.cpp",
	angle_dir .. "src/compiler/translator/ExtensionGLSL.h",
	angle_dir .. "src/compiler/translator/OutputGLSL.cpp",
	angle_dir .. "src/compiler/translator/OutputGLSL.h",
	angle_dir .. "src/compiler/translator/OutputGLSLBase.cpp",
	angle_dir .. "src/compiler/translator/OutputGLSLBase.h",
	angle_dir .. "src/compiler/translator/TranslatorGLSL.cpp",
	angle_dir .. "src/compiler/translator/TranslatorGLSL.h",
	angle_dir .. "src/compiler/translator/VersionGLSL.cpp",
	angle_dir .. "src/compiler/translator/VersionGLSL.h",
}

local angle_translator_lib_metal_sources = {
	angle_dir .. "src/compiler/translator/OutputVulkanGLSLForMetal.h",
	angle_dir .. "src/compiler/translator/OutputVulkanGLSLForMetal.mm",
	angle_dir .. "src/compiler/translator/TranslatorMetal.cpp",
	angle_dir .. "src/compiler/translator/TranslatorMetal.h",
}

local angle_preprocessor_sources = {
	angle_dir .. "src/compiler/preprocessor/DiagnosticsBase.cpp",
	angle_dir .. "src/compiler/preprocessor/DiagnosticsBase.h",
	angle_dir .. "src/compiler/preprocessor/DirectiveHandlerBase.cpp",
	angle_dir .. "src/compiler/preprocessor/DirectiveHandlerBase.h",
	angle_dir .. "src/compiler/preprocessor/DirectiveParser.cpp",
	angle_dir .. "src/compiler/preprocessor/DirectiveParser.h",
	angle_dir .. "src/compiler/preprocessor/ExpressionParser.h",
	angle_dir .. "src/compiler/preprocessor/Input.cpp",
	angle_dir .. "src/compiler/preprocessor/Input.h",
	angle_dir .. "src/compiler/preprocessor/Lexer.cpp",
	angle_dir .. "src/compiler/preprocessor/Lexer.h",
	angle_dir .. "src/compiler/preprocessor/Macro.cpp",
	angle_dir .. "src/compiler/preprocessor/Macro.h",
	angle_dir .. "src/compiler/preprocessor/MacroExpander.cpp",
	angle_dir .. "src/compiler/preprocessor/MacroExpander.h",
	angle_dir .. "src/compiler/preprocessor/Preprocessor.cpp",
	angle_dir .. "src/compiler/preprocessor/Preprocessor.h",
	angle_dir .. "src/compiler/preprocessor/SourceLocation.h",
	angle_dir .. "src/compiler/preprocessor/Token.cpp",
	angle_dir .. "src/compiler/preprocessor/Token.h",
	angle_dir .. "src/compiler/preprocessor/Tokenizer.h",
	angle_dir .. "src/compiler/preprocessor/numeric_lex.h",
	angle_dir .. "src/compiler/preprocessor/preprocessor_lex_autogen.cpp",
	angle_dir .. "src/compiler/preprocessor/preprocessor_tab_autogen.cpp",
}

StaticLibrary {
	Name = "angle_translator",

	Defines = {
		global_defines,
		"ANGLE_ENABLE_ESSL",
		{ "ANGLE_ENABLE_GLSL" ; Config = { "win*-*", "linux-*-*" } },
		{ "ANGLE_ENABLE_METAL" ; Config = "mac-*-*" },
	},

    Includes = {
		angle_dir .. "src/common/third_party/base",
		angle_dir .. "include",
		angle_dir .. "src",
    },

    Sources = {
		angle_translator_exported_headers,
		angle_translator_sources,
		angle_preprocessor_sources,
		{ angle_translator_lib_metal_sources ; Config = { "mac-*-*" } },
		{ angle_translator_glsl_sources ; Config = { "linux*-*", "win*-*" } },
    }
}

StaticLibrary {
	Name = "angle",

	Defines = {
		global_defines,
		gl_prototypes,
	},

    Includes = {
		angle_dir .. "src/common/third_party/base",
		angle_dir .. "include",
		angle_dir .. "src",
    },

    Sources = {
		libangle_image_util_sources,
		libangle_gpu_info_util_sources,
		libangle_image_util_headers,
		libangle_sources,
		libangle_headers,
		libangle_null_sources,
		libangle_gl_null_sources,
		libglesv2_sources,
		libangle_capture_sources,
		libangle_gl_sources,
		libegl_sources,
		-- TODO: Only build on Linux
		libangle_gl_glx_sources,
		-- { libangle_gl_sources ; Config = { "linux*-*", "win*-*" } },
    }
}

StaticLibrary {
	Name = "angle_common",

    Includes = {
		angle_dir .. "src/common/third_party/base",
		angle_dir .. "include",
		angle_dir .. "src",
    },

    Sources = {
    	common,
    },
}

StaticLibrary {
	Name = "angle_util",

    Includes = {
		angle_dir .. "include",
		samples_dir .. "sample_util",
		angle_dir .. "src",
		angle_dir,
    },

	Defines = {
		global_defines,
		gl_prototypes,
	},

	Sources = {
		util_dir .. "EGLPlatformParameters.h",
		-- util_dir .. "EGLWindow.cpp",
		-- util_dir .. "EGLWindow.h",
		util_dir .. "Event.h",
		util_dir .. "Matrix.cpp",
		util_dir .. "Matrix.h",
		util_dir .. "OSPixmap.h",
		util_dir .. "OSWindow.cpp",
		util_dir .. "OSWindow.h",
		util_dir .. "com_utils.h",
		util_dir .. "frame_capture_utils.h",
		util_dir .. "geometry_utils.cpp",
		util_dir .. "geometry_utils.h",
		util_dir .. "keyboard.h",
		util_dir .. "mouse.h",
		util_dir .. "random_utils.cpp",
		util_dir .. "random_utils.h",
		util_dir .. "shader_utils.cpp",
		util_dir .. "shader_utils.h",
		util_dir .. "util_export.h",
		util_dir .. "util_gl.h",
		util_dir .. "Timer.cpp",
		util_dir .. "Timer.h",
    	util_dir .. "test_utils.cpp",
    	util_dir .. "test_utils.h",
    	-- TODO: Linux/macOS
      	util_dir .. "posix/test_utils_posix.cpp",

		--{
    	 -- util_dir .. "windows/wgl_loader_autogen.cpp",
		--  util_dir .. "windows/win32/Win32Pixmap.cpp",
      	--  util_dir .. "windows/win32/Win32Pixmap.h",
        --  util_dir .. "windows/win32/Win32Window.cpp",
        --   util_dir .. "windows/win32/Win32Window.h"
        -- } ; Config = { "win*-*" },
	    --{
		  util_dir .. "x11/X11Pixmap.cpp",
		  util_dir .. "x11/X11Pixmap.h",
		  util_dir .. "x11/X11Window.cpp",
		  util_dir .. "x11/X11Window.h",
        --} ; Config = { "linux*-*" },
		--{
    	  -- util_dir .. "osx/OSXPixmap.h",
    	  -- util_dir .. "osx/OSXPixmap.mm",
    	  -- util_dir .. "osx/OSXWindow.h",
    	  -- util_dir .. "osx/OSXWindow.mm",
        --} ; Config = { "mac*-*" },
    },

}

StaticLibrary {
	Name = "angle_util_2",

    Includes = {
		angle_dir .. "include",
		samples_dir .. "sample_util",
		angle_dir .. "src",
		angle_dir,
    },

	Defines = {
		global_defines,
		gl_prototypes,
	},

	Sources = {
		util_dir .. "EGLWindow.cpp",
		util_dir .. "EGLWindow.h",
    },
}

StaticLibrary {
	Name = "angle_sample_util",

    Includes = {
		angle_dir .. "include",
		samples_dir .. "sample_util",
		angle_dir .. "src",
		angle_dir,
    },

	Defines = {
		global_defines,
		no_gl_prototypes,
	},

	Sources = {
    	util_dir .. "egl_loader_autogen.cpp",
    	util_dir .. "gles_loader_autogen.cpp",


    	samples_dir .. "sample_util/SampleApplication.cpp",
    	samples_dir .. "sample_util/SampleApplication.h",
    	samples_dir .. "sample_util/texture_utils.cpp",
    	samples_dir .. "sample_util/texture_utils.h",
    	samples_dir .. "sample_util/tga_utils.cpp",
    	samples_dir .. "sample_util/tga_utils.h",
    },
}

--[[
if (is_win) {
  _util_sources += [ "windows/WGLWindow.h" ]
  if (!angle_is_winuwp) {
    _util_sources += [
      "windows/win32/Win32Pixmap.cpp",
      "windows/win32/Win32Pixmap.h",
      "windows/win32/Win32Window.cpp",
      "windows/win32/Win32Window.h",
    ]
  }
}

if (angle_use_x11) {
  _util_sources += [
    "x11/X11Pixmap.cpp",
    "x11/X11Pixmap.h",
    "x11/X11Window.cpp",
    "x11/X11Window.h",
  ]
}

if (is_fuchsia) {
  _util_sources += [
    "fuchsia/ScenicWindow.cpp",
    "fuchsia/ScenicWindow.h",
  ]
} else if (use_ozone) {
  _util_sources += [
    "ozone/OzonePixmap.cpp",
    "ozone/OzoneWindow.cpp",
    "ozone/OzoneWindow.h",
  ]
}

if (is_mac) {
  _util_sources += [
    "osx/OSXPixmap.h",
    "osx/OSXPixmap.mm",
    "osx/OSXWindow.h",
    "osx/OSXWindow.mm",
  ]
}

if (is_android) {
  _util_sources += [
    "android/AndroidPixmap.cpp",
    "android/AndroidWindow.cpp",
    "android/AndroidWindow.h",
    "android/third_party/android_native_app_glue.c",
    "android/third_party/android_native_app_glue.h",
  ]
}


    	samples_dir .. "sample_util/SampleApplication.cpp",
    	samples_dir .. "sample_util/SampleApplication.h",
    	samples_dir .. "sample_util/texture_utils.cpp",
    	samples_dir .. "sample_util/texture_utils.h",
    	samples_dir .. "sample_util/tga_utils.cpp",
    	samples_dir .. "sample_util/tga_utils.h",
	}
}
--]]

--[[
[232/4232] ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/samples/hello_triangle/HelloTriangle.o.d
	-DUSE_UDEV
	-DUSE_AURA=1
	-DUSE_GLIB=1
	-DUSE_NSS_CERTS=1
	-DUSE_X11=1
	-D_FILE_OFFSET_BITS=64
	-D_LARGEFILE_SOURCE
	-D_LARGEFILE64_SOURCE
	-D_GNU_SOURCE
	-DCR_CLANG_REVISION=\"n344329-9284abd0-6\"
	-D__STDC_CONSTANT_MACROS
	-D__STDC_FORMAT_MACROS
	-DCOMPONENT_BUILD
	-DCR_SYSROOT_HASH=79a7783607a69b6f439add567eb6fcb48877085c
	-D_DEBUG
	-DDYNAMIC_ANNOTATIONS_ENABLED=1
	-DANGLE_IS_64_BIT_CPU
	-DGL_GLES_PROTOTYPES=0
	-DEGL_EGL_PROTOTYPES=0
	-DANGLE_USE_UTIL_LOADER
	-I../../include -I../../src -I../../samples/sample_util
	-I../../src/common/third_party/base
	-Igen/angle
	-I../../include
	-I../..
	-I../..
	-I../..
	-fno-strict-aliasing
	--param=ssp-buffer-size=4
	-fstack-protector
	-funwind-tables
	-fPIC
	-pthread
	-fcolor-diagnostics
	-fmerge-all-constants
	-fcrash-diagnostics-dir=../../tools/clang/crashreports
	-Xclang
	-mllvm
	-Xclang
	-instcombine-lower-dbg-declare=0
	-m64
	-march=x86-64
	-Wno-builtin-macro-redefined
	-D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -O0 -fno-omit-frame-pointer -g2 -Xclang -debug-info-kind=constructor -gsplit-dwarf -ggnu-pubnames -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wconditional-uninitialized -Wextra-semi-stmt -Wfloat-conversion -Winconsistent-missing-destructor-override -Wmissing-field-initializers -Wnon-virtual-dtor -Wredundant-parens -Wshadow-field -Wtautological-type-limit-compare -Wundefined-reinterpret-cast -Wunneeded-internal-declaration -Wparentheses -Wrange-loop-analysis -Wstrict-prototypes -Wunreachable-code -Wshorten-64-to-32 -Wno-undefined-bool-conversion
	-Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti
	--sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden
	-c ../../samples/hello_triangle/HelloTriangle.cpp -o obj/samples/hello_triangle/HelloTriangle.o
--]]




Program {
    Name = "hello_triangle",

	Defines = {
		"ANGLE_USE_UTIL_LOADER",
		global_defines,
		no_gl_prototypes,
	},

    Includes = {
		angle_dir .. "include",
		angle_dir .. "src",
		samples_dir .. "sample_util",
		angle_dir .. "src/common/third_party/base",
    	angle_dir
    },

    -- Env = {
-- 		PROGCOM = {
-- 			{  "-lx11", "-ldl"; Config = "linux-*-*" },
-- 		},
-- 	},

    Sources = { samples_dir .. "hello_triangle/HelloTriangle.cpp" },

	Libs = {
		{ "X11", "dl", "pthread" ; Config = "linux-*-*" },
	},

    Depends = { "angle_sample_util", "angle_util_2", "angle", "angle_util", "angle_translator", "angle_common" },
}

Always "hello_triangle"
