[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
flowi = { path = "../crates/flowi" }
json5 = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

