///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "image.h"
#include "layout.h"
#include "manual.h"
#include "math_data.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum FlPainterLayer {

    FlPainterLayer_ActiveWindow = 0,

    FlPainterLayer_Background = 1,

    FlPainterLayer_Foreground = 2,
} FlPainterLayer;

#include "painter.inl"
#ifdef __cplusplus
}
#endif
