///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "image.h"
#include "manual.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef uint64_t FlTexture;

typedef struct FlRenderer {
} FlRenderer;

// Get a texture from the active Renderer given a image handle. The renderer can return None if the image handle isnt't
// valid or that that image hasn't been created as a texture yet
static FlTexture fl_renderer_get_texture(FlImage image);

#include "renderer.inl"
#ifdef __cplusplus
}
#endif
