[package]
name = "testbed"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
minifb = "0.19.2"
egui = { path = "../egui" }

