[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon,+neon_fp16,+neon_v8_2_a"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=cortex-a76", "-C", "target-feature=+neon,+neon_fp16,+neon_v8_2_a,+crc,+fcma,+crypto"]
