[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=cortex-a76",
    "-C", "link-arg=-pthread",
#    "-C", "link-args=-Wl,--dynamic-linker=/lib/ld-linux-aarch64.so.1",
]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]
