[package]
name = "flowi"
version = "0.1.0"
edition = "2021"

[dependencies]
flowi_core = { path = "../flowi_core" }
flowi_sw_renderer = { path = "../flowi_sw_renderer" }

[dependencies.sdl2]
version = "0.37"
default-features = false
features = ["bundled", "unsafe_textures"]
