[package]
name = "test_bed"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27"
clay-layout = { git = "https://github.com/clay-ui-rs/clay" }
ui_raster = { path = "../ui_raster" }

[features]
default = []
