[package]
name = "sw_raster_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sw_rasterizer = { path = "../sw_rasterizer" }
minifb = "0.25.0"
byteorder = "1"

[features]
timing_enabled = []

