#[allow(non_camel_case_types,dead_code,non_upper_case_globals,non_snake_case,improper_ctypes)]
pub mod kernel {
/* automatically generated by rust-bindgen 0.69.5 */

extern "C" {
    pub fn draw_rects(
        output: *mut i16,
        tile_width: i32,
        tile_height: i32,
        tile_offset_x: f32,
        tile_offset_y: f32,
        rect_min_x: *mut f32,
        rect_min_y: *mut f32,
        rect_max_x: *mut f32,
        rect_max_y: *mut f32,
        corner_colors: *mut f32,
        count: i32,
    );
}
}